<a href="https://colab.research.google.com/github/bala5071/Machine-Learning/blob/main/Car_Evaluation_KNN_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [ ]:
data = pd.read_csv('car.data')
print(data.head())

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc


In [ ]:
X = data[['buying',
      'maint',
      'safety']].values
y = data[['class']]
print(X)
print(y)

[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]
      class
0     unacc
1     unacc
2     unacc
3     unacc
4     unacc
...     ...
1723   good
1724  vgood
1725  unacc
1726   good
1727  vgood

[1728 rows x 1 columns]


converion of X to data points

In [ ]:
Le = LabelEncoder()
for i in range(len(X[0])):
  X[:, i] = Le.fit_transform(X[:, i])
print(X)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


converion y into data points

In [ ]:
label_mapping = {
    'unacc':0,
    'acc':1,
    'good':2,
    'vgood':3,
}
y['class'] = y['class'].map(label_mapping)
y = np.array(y)
print(y)

[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


<ipython-input-14-e892331f4307>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['class'] = y['class'].map(label_mapping)


create model

In [ ]:
knn = neighbors.KNeighborsClassifier(n_neighbors=25,weights='uniform')

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

knn.fit(X_train, y_train)

prediction = knn.predict(X_test)

accuracy = metrics.accuracy_score(y_test, prediction)

print('Prediction:', prediction)
print('Accuracy:', accuracy)

Prediction: [0 0 0 3 0 0 0 1 0 0 1 0 0 0 0 3 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 3 0 0 0 0 1 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0
 1 0 0 0 0 3 1 0 1 0 1 1 0 1 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1
 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 3 0 0 0 3 1 1 0 1 3 1 1 0 1 1 0 0
 0 0 1 1 0 0 0 0 1 0 1 1 0 0 1 1 0 0 0 1 1 1 0 0 1 0 1 0 0 0 1 0 1 0 0 1 0
 0 3 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 3 0 0 0 1 0 1 0 1 0 1 0 1 3 0 1 0 0
 1 1 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0
 0 0 1 0 0 0 0 0 3 1 0 3 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 3 1 0 0 1 1 0 0 3 0
 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 3 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 0 0 3 0 0 3 3 0 0 0 0]
Accuracy: 0.7254335260115607


/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [ ]:
a = 1500
print('actual value:', y[a])
print('predicted value:', knn.predict(X)[a])

actual value: [0]
predicted value: 0
